// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3gO3sHvEgyFVJNUjohIGmqG-pyA9i-zg',
    appId: '1:720682910769:web:00ff3336805a5189cd4110',
    messagingSenderId: '720682910769',
    projectId: 'chat-app-588be',
    authDomain: 'chat-app-588be.firebaseapp.com',
    storageBucket: 'chat-app-588be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCypdgThRCWV9fcRb2YFMBM-J_I85O1JCI',
    appId: '1:720682910769:android:6eaa17c8fb8b3b98cd4110',
    messagingSenderId: '720682910769',
    projectId: 'chat-app-588be',
    storageBucket: 'chat-app-588be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn_3D3NOsBb6x7x9Ln1M87xI-wDC5TY6o',
    appId: '1:720682910769:ios:1a93b20607f20345cd4110',
    messagingSenderId: '720682910769',
    projectId: 'chat-app-588be',
    storageBucket: 'chat-app-588be.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn_3D3NOsBb6x7x9Ln1M87xI-wDC5TY6o',
    appId: '1:720682910769:ios:1a93b20607f20345cd4110',
    messagingSenderId: '720682910769',
    projectId: 'chat-app-588be',
    storageBucket: 'chat-app-588be.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3gO3sHvEgyFVJNUjohIGmqG-pyA9i-zg',
    appId: '1:720682910769:web:e67d749439ff10eacd4110',
    messagingSenderId: '720682910769',
    projectId: 'chat-app-588be',
    authDomain: 'chat-app-588be.firebaseapp.com',
    storageBucket: 'chat-app-588be.appspot.com',
  );
}
